# USB 장치 이름 설정
CONFIG_ZMK_KEYBOARD_NAME="alish40"

# HID(키보드) 리포트 활성화
CONFIG_ZMK_USB=y

# --- ZMK Studio 설정 ---
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# 블루투스
CONFIG_ZMK_BLE=y
CONFIG_BT_MAX_CONN=5
CONFIG_BT_MAX_PAIRED=5
CONFIG_ZMK_BATTERY_REPORTING=y

# --- 기타 설정 ---
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# 1. 일정 시간 입력이 없으면 LED를 먼저 끕니다 (밀리초 단위, 30초)
CONFIG_ZMK_IDLE_TIMEOUT=30000
# 2. 깊은 절전 모드(Deep Sleep) 활성화
CONFIG_ZMK_SLEEP=y
# 3. 15분(900,000ms) 동안 입력이 없으면 Deep Sleep 진입
# 이 상태에서는 아무 키나 누르면 다시 깨어납니다! (중요)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
# 4. soft off. 리셋버튼 누르거나 usb 꽂아야
CONFIG_ZMK_PM_SOFT_OFF=y

# --- RGB Underglow 설정 ---
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_LED_STRIP=y

# RGB 전원 제어를 위한 설정 (overlay의 ext_power 노드와 연결됨)
CONFIG_ZMK_EXT_POWER=y
# RGB 기능을 조작할 때 외부 전원을 자동으로 켜는 기능을 끔
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n

# RGB 하위 설정들
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=y
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=1
