# USB 장치 이름 설정
CONFIG_ZMK_KEYBOARD_NAME="alish40"

# HID(키보드) 리포트 활성화
CONFIG_ZMK_USB=y

# --- ZMK Studio 설정 ---
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# 블루투스
CONFIG_ZMK_BLE=y
CONFIG_BT_MAX_CONN=5
CONFIG_BT_MAX_PAIRED=5
# 배터리 리포트가 전에는 없었던 기능 같아서 꺼봄
CONFIG_ZMK_BATTERY_REPORTING=n

# --- 기타 설정 ---
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_ZMK_BLE_EXPERIMENTAL_SEC=y

# 1. 일정 시간 입력이 없으면 LED를 먼저 끕니다 (밀리초 단위, 30초)
CONFIG_ZMK_IDLE_TIMEOUT=30000
# 2. 깊은 절전 모드(Deep Sleep) 활성화
CONFIG_ZMK_SLEEP=y
# 3. 15분(900,000ms) 동안 입력이 없으면 Deep Sleep 진입
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
# 4. soft off. 리셋버튼 누르거나 usb 꽂아야
CONFIG_ZMK_PM_SOFT_OFF=y

# --- RGB Underglow 설정 ---
CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_LED_STRIP=y ---이거 대신 밑에 거 쓰라고 함
CONFIG_WS2812_STRIP=y
CONFIG_SPI=y

# RGB 전원 제어를 위한 설정 (overlay의 ext_power 노드와 연결됨)
CONFIG_ZMK_EXT_POWER=y
# 유휴 상태일 때 RGB 자동 꺼짐 활성화
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y

# RGB 하위 설정들
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=y
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=2
